// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBL1kiS_Y32p2Vtfgzk5ScMS8g_U7oPiyc',
    appId: '1:1061829821598:web:c2e956b025f65faf64a78f',
    messagingSenderId: '1061829821598',
    projectId: 'firebase-coba-0502',
    authDomain: 'fir-coba-0502.firebaseapp.com',
    storageBucket: 'firebase-coba-0502.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAXHlmWO3K6rf-30B86gGzCiGWNW7HrAcY',
    appId: '1:1061829821598:android:8614a7c08d2fd38d64a78f',
    messagingSenderId: '1061829821598',
    projectId: 'firebase-coba-0502',
    storageBucket: 'firebase-coba-0502.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCcS2oBLnGpyvpPRy025xe0w6j_sFIW5Wc',
    appId: '1:1061829821598:ios:93cbab8c57d5478164a78f',
    messagingSenderId: '1061829821598',
    projectId: 'firebase-coba-0502',
    storageBucket: 'firebase-coba-0502.appspot.com',
    iosBundleId: 'com.example.flutterlist',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCcS2oBLnGpyvpPRy025xe0w6j_sFIW5Wc',
    appId: '1:1061829821598:ios:93cbab8c57d5478164a78f',
    messagingSenderId: '1061829821598',
    projectId: 'firebase-coba-0502',
    storageBucket: 'firebase-coba-0502.appspot.com',
    iosBundleId: 'com.example.flutterlist',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBL1kiS_Y32p2Vtfgzk5ScMS8g_U7oPiyc',
    appId: '1:1061829821598:web:a96f05d923bb87e864a78f',
    messagingSenderId: '1061829821598',
    projectId: 'firebase-coba-0502',
    authDomain: 'fir-coba-0502.firebaseapp.com',
    storageBucket: 'firebase-coba-0502.appspot.com',
  );

}